### ISSUE TITLE
Add model profiling as feature

### ISSUE THREAD

**Issue by marvinbuss** [Azure/aml-deploy#2]
Model profiling would be a nice feature to add. Alternatively, we could create a new Action for this feature to simplify the Action.

**Comment by ashishonce** [comment]
I am currently looking into this. 
I found that profiling will also require us to look for Data set which user wants to put into his profiling. 
We might want to support user to mention his DataSet , 
both Tabular and File based , also do we want to support putting of data from local-github repo to DataSet and then put it into profiling?

**Comment by marvinbuss** [comment]
@ashishonce Good point. This is probably not required, if the user has already registered the model correctly with input dataset.
This means we have to add another parameter for profiling (e.g. `profiling_enabled`, `profiling_input_dataset`)?

**Comment by ashishonce** [comment]
That is true, if he has registered an existing data set. what I meant was, are we thinking about allowing people to create/register new data set from nay of our actions? Data might be in their repository

**Comment by marvinbuss** [comment]
Yes, I started working on a data GH Action. I can work on this later this or next week and release a first version.
