### ISSUE TITLE
Deploy model to Azure function

### ISSUE THREAD

**Issue by marvinbuss** [Azure/aml-deploy#6]
- [ ] Enable deployment to Azure function

**Comment by marvinbuss** [comment]
I am suggesting that we enable that only the Docker image is built and pulled to the GH Action runner. We can then provide the docker image as output and the user can deploy it anywhere they want using other available GitHub Actions: 
* https://github.com/Azure/functions-container-action
* https://github.com/Azure/webapps-deploy

**Comment by totosan** [comment]
That would be an awesome feature. I support the idea of keeping the deployment of a model decoupled from the target. So having "only" a container image would feet all needs. The rest of work could then be in the responsibility of the developer creating the pipeline.

**Comment by marvinbuss** [comment]
@totosan 
I created this branch to implement the feature. I did not have time yet to test the feature. Feel free to give it a try. The new version will output ACR address, username and password (all masked) if you enable it with the parameter `create_image`. You can then use these outputs to deploy to a Function or somewhere else.
You can also skip the deployment with the parameter `skip_deployment`.

**Comment by totosan** [comment]
@marvinbuss 
I'll give it a shot and come back with feedback later on. Thx!

**Comment by totosan** [comment]
I was able to test this branch and it worked like a charm. I am very happy to have you acting like a rocket. Cheers!

**Comment by totosan** [comment]
By the way, it would be great, to have a kind of example in the repo, to run the container as AzFunction. Because, the aml sdk is building an entrypoint (`main.py`) in the image, where a function starts it own host.

**Comment by marvinbuss** [comment]
Do you have an example of the `main.py` that is created?
We will merge this branch soon after running some additional tests. So feel free to suggest additional changes before merging this into master.

**Comment by ashishonce** [comment]
deploy to Azure functions functionality is a very much required and intuitive when we think about a pre-production environment and even staging or testing environment, when user requirement might just be spinning a function app asap and testing. 
having said that.. 
@marvinbuss if we provide them a docker image?.. do we fully understand their environment and dependencies for creating, or will we provide some kind of base-image?

**Comment by totosan** [comment]
@marvinbuss I'll provide you the main.py tomorrow. Need only to pull the image and extract that little piece 👍
@ashishonce you are probably right. The current solution, creating only an image, is a good solution for a generalized version. This can act as a WebAPI or container app. This can be hosted directly in Azure App Service or locally,... Hosting this as Azure Function is not trivial without hacks (I tried that) . So, I think we should also have an extra option to create a function image. The AML SDK cannot be used for this.

**Comment by marvinbuss** [comment]
@totosan Thank you for your help! That's great! Did you try to run this Action with the Image that we are providing: https://github.com/Azure/functions-container-action ?

@ashishonce The image we are providing is the one that would also be used for a deployment on AKS or ACI.  We are just packaging the model in the branch and provide the ACR details as output. The user can decide whether the deployment should still happen on ACR or AKS for testing purposes. This feature is still super helpful, if the user wants to deploy on-prem or on AWS or GCP. They are then free to do whatever they want with the docker image.

I agree that a deployment to a function would be very helpful. At the same time, the feature is still very much in preview. Let's look at how we can enable this easily.

**Comment by totosan** [comment]
@marvinbuss I am just using this here: 
{
    "inference_source_directory": "MLSolution/EyeSegmentation/",
    "inference_entry_script": "score.py",
    "conda_file": "environment.yml",
    "runtime": "python",
    "enable_gpu": false,
    "description": "first test container",
    "skip_deployment": true,
    "create_image": true
}
(deploy.json)
..means, that this action is using the AKS-BaseImage, right? If I pass BaseImage of Azure Function, this wouldn't work, because I is no logic, that decides, where to embed the scoring file and model.

But the solution with image-only is good enough. If I want to create a Function instead, I can also grab the model and write the scoring file, push these into the BaseImage of AzFunction and fire it up into Azure.

**Comment by totosan** [comment]
@marvinbuss This is the main.py file from the output image of aml-deploy.
Settings are the same as above in deploy.json
[Main.py](https://gist.github.com/totosan/acf5b3405c37c7eb10f52b600d2e2da6#file-main-py)

**Comment by marvinbuss** [comment]
@totosan Let me test this later today or tomorrow.
I might have an idea how this can work.

**Comment by marvinbuss** [comment]
@totosan Sadly my idea did not work out.

I hope you noticed that you can also pull down all outputs in the aml-run action to do whatever you want with the model after training it on Azure ML.

We could package the model in a way, so that you could deploy it easily to an azure function. We would have to install a preview feature ("[azureml-contrib-functions](https://docs.microsoft.com/en-us/python/api/azureml-contrib-functions/azureml.contrib.functions?view=azure-ml-py)") into the docker image and then we would have to add some more options.

**Comment by marvinbuss** [comment]
@totosan @ashishonce I created another branch, which would allow creating different kind of images (normal docker, functions blob, etc.). Please take a look. 
It should be possible to use this after building the correct image: https://github.com/Azure/functions-container-action

**Comment by marvinbuss** [comment]
@totosan Have you seen the new branch. It allows you to create a docker image that is ready for deployment on a Function. The trigger can also be selected (http, blob, etc.).

**Comment by totosan** [comment]
@marvinbuss I am still on evaluation. First tests seem to be promising. But I try to get, how to integrate my conferencing code into. My first tests show, that images are built very well, but without my custom code from inferencing folder. Maybe, I missed something. But nevertheless, I keep investigating it and do some other tests. I'll be optimistic, to get with a success note in the afternoon.

**Comment by totosan** [comment]
No luck! What is the expected input, to have a running function? From my understanding, I need a deploy.json with create_image : function_http (e.g.) and a score.py, for conferencing. But Azure Function also needs a kind of __init__.py (main function with trigger binding). When attaching to the container, that is produced, I cannot get a clue, how the function host can magically find my entry point.

**Comment by marvinbuss** [comment]
@totosan We are currently running some tests. Let us get back to you, once we have tested this properly.

**Comment by marvinbuss** [comment]
@totosan There seems to be an issue with the Docker images that are created by the SDK. We will synch internally to fix this. I also opened an issue here: https://github.com/Azure/functions-container-action/issues/5

**Comment by marvinbuss** [comment]
@totosan There will be a server side fix soon. We will keep you updated. As soon as the fix has been implemented, we will merge the feature into master and update the release.

**Comment by marvinbuss** [comment]
@totosan Sadly, it takes another week until the fix is rolled out to all regions. We are doing our best, but this is not in our hands. 👎

**Comment by totosan** [comment]
@marvinbuss Thanks for giving the state. I'll deal with :-)

**Comment by marvinbuss** [comment]
@totosan Our tests have shown that the bug was fixed.
We will merge the changes soon into master and release a new version to enable deployments to Azure Functions.

**Comment by marvinbuss** [comment]
Here is some sample code:

```python
import requests
import json

# URL for the web service.
scoring_uri = "<function-url>"

# Two sets of data to score, so we get two results back.
data = {"data": [[ 1,2,3,4 ], [ 10,9,8,7 ]]}

# Convert to JSON string.
input_data = json.dumps(data)

# Set the content type.
headers = {'Content-Type': 'application/json'}

# Make the request and display the response.
resp = requests.post(scoring_uri, input_data, headers=headers)
print(resp.text)
```

**Comment by marvinbuss** [comment]
I have released a new version, which allows creating images that can be deployed to an Azure Function. More details can be found here: https://github.com/Azure/aml-deploy/releases/tag/v1.6.1
